FROM node:20-alpine

WORKDIR /app

# パッケージをインストールするためにrootユーザーを使用
COPY app/package*.json ./
RUN npm install

# アプリケーションのソースコードをコピー
COPY app ./

# node_modulesの所有者を変更
RUN chown -R node:node /app

# 非rootユーザーに切り替え
USER node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]