FROM node:20-alpine

WORKDIR /app

# パッケージをインストールするためにrootユーザーを使用
COPY app/package*.json ./
RUN npm install

# Tailwind CSSとその依存関係をインストール
RUN npm install -D tailwindcss@latest postcss@latest autoprefixer@latest

# アプリケーションのソースコードをコピー
COPY app ./

# Tailwind CSSの設定ファイルを生成
RUN npx tailwindcss init -p

# Tailwind CSSをビルド
# RUN npm run build:css

# node_modulesの所有者を変更
RUN chown -R node:node /app

# 非rootユーザーに切り替え
USER node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]