FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

# appディレクトリを作成
RUN mkdir -p /app/app

# entrypoint.shをコピー
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# 既存のappディレクトリの内容をコピー（node_modules以外）
COPY app /app/app
# RUN rm -rf /app/app/node_modules

WORKDIR /app/app

EXPOSE 5173

CMD ["/bin/sh", "/app/entrypoint.sh"]